plugins {
	id 'net.fabricmc.fabric-loom-remap' version "${loom_version}"
	id 'maven-publish'
}

repositories {
	mavenCentral()
	maven { url = "https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/" }
	maven { url = "https://maven.meteordev.org/snapshots" }
	maven { url = "https://babbaj.github.io/maven/" }
}

loom {
	mods {
		"delta-client" {
			sourceSet sourceSets.main
		}
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings "net.fabricmc:yarn:1.21.4+build.8:v2"
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
	modImplementation "software.bernie.geckolib:geckolib-fabric-1.21.4:4.8.5"
	modImplementation "meteordevelopment:baritone:${project.minecraft_version}-SNAPSHOT"
	// Baritone кладёт эту нативную либу как вложенный jar, а в dev-окружении JiJ не распаковывается
	runtimeOnly "dev.babbaj:nether-pathfinder:1.4.1"

	implementation 'com.google.code.findbugs:jsr305:3.0.2'
	include 'com.google.code.findbugs:jsr305:3.0.2'
	implementation 'com.google.code.gson:gson:2.11.0'
	include 'com.google.code.gson:gson:2.11.0'
	implementation 'com.google.errorprone:error_prone_annotations:2.27.0'
	include 'com.google.errorprone:error_prone_annotations:2.27.0'
	implementation 'org.apache.commons:commons-lang3:3.18.0'
	include 'org.apache.commons:commons-lang3:3.18.0'
	implementation 'org.apache.logging.log4j:log4j-api:2.24.1'
	include 'org.apache.logging.log4j:log4j-api:2.24.1'
	implementation 'org.java-websocket:Java-WebSocket:1.5.6'
	include 'org.java-websocket:Java-WebSocket:1.5.6'
	implementation 'org.javassist:javassist:3.28.0-GA'
	include 'org.javassist:javassist:3.28.0-GA'
	implementation 'org.json:json:20250107'
	include 'org.json:json:20250107'
	implementation 'org.jsoup:jsoup:1.18.3'
	include 'org.jsoup:jsoup:1.18.3'
	implementation 'org.reflections:reflections:0.10.2'
	include 'org.reflections:reflections:0.10.2'
	implementation 'org.slf4j:slf4j-api:2.0.6'
	include 'org.slf4j:slf4j-api:2.0.6'
	
	compileOnly 'org.projectlombok:lombok:1.18.30'
	annotationProcessor 'org.projectlombok:lombok:1.18.30'
	compileOnly 'org.osgi:osgi.core:8.0.0'
	compileOnly 'biz.aQute.bnd:biz.aQute.bnd.annotation:6.4.0'
	compileOnly 'org.osgi:osgi.annotation:8.0.0'
}

processResources {
	def version = project.version
	inputs.property "version", version

	filesMatching("fabric.mod.json") {
		expand "version": version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 21
	it.options.compilerArgs << "-Xmaxerrs" << "9999999"
}

java {
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
}

jar {
	def projectName = project.name
	inputs.property "projectName", projectName

	from("LICENSE") {
		rename { "${it}_$projectName"}
	}
}

publishing {
	publications {
		create("mavenJava", MavenPublication) {
			from components.java
		}
	}
}
